### ISSUE TITLE
Demo not working on Chrome Version 78.0.3904.108 (Build officiel) (64 bits)

### ISSUE THREAD

**Issue by Cotting** [OpendataCH/swiss-transport-flows#1]
The demo is working on FF but not on Chrome.

**Comment by loleg** [comment]
I am going to close this issue because A) it hasn't been answered in 2 years, sorry, .. and B) has too few details for a diagnosis. We would want to check the console etc. The fact that the site is completely broken in both browsers is discussed in #2
